title: sa11y
email: lukeylias@gmail.com
description: >-
  sa11y is a tool that provides easy-to-follow steps for beginners to review website accessibility.
baseurl: ""
url: "http://sa11y.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
